name: Release (Linux)

on:
  push:
    tags: ["v*-linux"]   # e.g. v1.0.4-linux
  workflow_dispatch: {}  # allow manual runs

permissions:
  contents: write        # needed to create/update releases

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install system deps (venv)
        run: sudo apt-get update && sudo apt-get install -y python3-venv

      - name: Install npm deps
        run: npm ci

      - name: Build renderer
        run: npm run build

      # Build a Python venv that includes 'concepts' and ship it with the app
      - name: Build Python venv
        run: |
          python3 -m venv python-venv
          ./python-venv/bin/pip install --upgrade pip
          ./python-venv/bin/pip install concepts

      - name: Package (no auto-publish)
        run: npx electron-builder --linux AppImage deb --publish=never

      - name: List artifacts
        run: ls -lh release || true

      - name: Create / Update GitHub Release (attach artifacts)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}                 # e.g. v1.0.4-linux
          name: "Lattice ${{ github.ref_name }}"
          allowUpdates: true
          replacesArtifacts: true
          draft: false
          prerelease: false
          artifacts: |
            release/*.AppImage
            release/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
